# Generated by Django 4.1.2 on 2022-10-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserCustom',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
