# Generated by Django 4.1.2 on 2022-10-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0004_rename_user_usercustom_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCustom',
            new_name='User',
        ),
    ]
